import type { Alert, Student, TeamMember } from "./types";
import { FULL_WEEK, MWF, TTH } from "./types";

export const CURRENT_USER = {
  name: "Maya Chen",
  email: "maya.chen@littlenest.care",
  role: "Manager" as const,
  avatar: "MC",
  center: "Little Nest Learning Center",
};

export const STUDENTS: Student[] = [
  {
    id: "st-001",
    firstName: "Ava",
    lastName: "Patel",
    preferredName: "Avi",
    dob: "2025-06-12",
    classroomId: "shark",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Priya Patel",
    guardianEmail: "priya.patel@email.com",
    guardianPhone: "(503) 555-0142",
    enrollmentDate: "2026-02-03",
    notes: "Dairy sensitivity — oat milk only.",
  },
  {
    id: "st-002",
    firstName: "Leo",
    lastName: "Nguyen",
    dob: "2025-04-28",
    classroomId: "shark",
    schedule: MWF,
    pottyTrained: false,
    status: "active",
    guardianName: "Minh Nguyen",
    guardianEmail: "minh.nguyen@email.com",
    guardianPhone: "(503) 555-0198",
    enrollmentDate: "2025-11-10",
  },
  {
    id: "st-003",
    firstName: "Sofia",
    lastName: "Reyes",
    dob: "2025-03-15",
    classroomId: "octopus",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Carmen Reyes",
    guardianEmail: "carmen.reyes@email.com",
    guardianPhone: "(971) 555-0114",
    enrollmentDate: "2025-09-02",
  },
  {
    id: "st-004",
    firstName: "Jonah",
    lastName: "Brooks",
    dob: "2025-01-20",
    classroomId: "octopus",
    schedule: TTH,
    pottyTrained: false,
    status: "active",
    guardianName: "Ellen Brooks",
    guardianEmail: "ellen.brooks@email.com",
    guardianPhone: "(503) 555-0177",
    enrollmentDate: "2025-08-18",
  },
  {
    id: "st-005",
    firstName: "Mia",
    lastName: "Okonkwo",
    dob: "2024-11-08",
    classroomId: "octopus",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Amara Okonkwo",
    guardianEmail: "amara.okonkwo@email.com",
    guardianPhone: "(971) 555-0163",
    enrollmentDate: "2025-06-01",
  },
  {
    id: "st-006",
    firstName: "Noah",
    lastName: "Kim",
    dob: "2024-08-22",
    classroomId: "starfish",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Ji-eun Kim",
    guardianEmail: "jieun.kim@email.com",
    guardianPhone: "(503) 555-0129",
    enrollmentDate: "2025-03-15",
  },
  {
    id: "st-007",
    firstName: "Isla",
    lastName: "Martinez",
    dob: "2024-06-30",
    classroomId: "starfish",
    schedule: MWF,
    pottyTrained: false,
    status: "active",
    guardianName: "Diego Martinez",
    guardianEmail: "diego.martinez@email.com",
    guardianPhone: "(503) 555-0188",
    enrollmentDate: "2025-01-06",
  },
  {
    id: "st-008",
    firstName: "Ethan",
    lastName: "Walsh",
    dob: "2024-05-14",
    classroomId: "starfish",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Sarah Walsh",
    guardianEmail: "sarah.walsh@email.com",
    guardianPhone: "(971) 555-0102",
    enrollmentDate: "2024-12-02",
  },
  {
    id: "st-009",
    firstName: "Zoe",
    lastName: "Hassan",
    dob: "2024-03-03",
    classroomId: "dolphin",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Layla Hassan",
    guardianEmail: "layla.hassan@email.com",
    guardianPhone: "(503) 555-0155",
    enrollmentDate: "2024-10-14",
  },
  {
    id: "st-010",
    firstName: "Caleb",
    lastName: "Foster",
    dob: "2024-01-19",
    classroomId: "dolphin",
    schedule: TTH,
    pottyTrained: true,
    status: "active",
    guardianName: "Brian Foster",
    guardianEmail: "brian.foster@email.com",
    guardianPhone: "(503) 555-0133",
    enrollmentDate: "2024-09-03",
  },
  {
    id: "st-011",
    firstName: "Harper",
    lastName: "Singh",
    dob: "2023-11-25",
    classroomId: "dolphin",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Anika Singh",
    guardianEmail: "anika.singh@email.com",
    guardianPhone: "(971) 555-0191",
    enrollmentDate: "2024-07-22",
  },
  {
    id: "st-012",
    firstName: "Lucas",
    lastName: "Berg",
    dob: "2023-07-08",
    classroomId: "turtle",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Ingrid Berg",
    guardianEmail: "ingrid.berg@email.com",
    guardianPhone: "(503) 555-0147",
    enrollmentDate: "2024-04-01",
  },
  {
    id: "st-013",
    firstName: "Emma",
    lastName: "Torres",
    dob: "2023-05-17",
    classroomId: "turtle",
    schedule: MWF,
    pottyTrained: true,
    status: "active",
    guardianName: "Rosa Torres",
    guardianEmail: "rosa.torres@email.com",
    guardianPhone: "(503) 555-0166",
    enrollmentDate: "2024-02-12",
  },
  {
    id: "st-014",
    firstName: "Owen",
    lastName: "Clarke",
    dob: "2023-03-29",
    classroomId: "turtle",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "James Clarke",
    guardianEmail: "james.clarke@email.com",
    guardianPhone: "(971) 555-0120",
    enrollmentDate: "2023-11-06",
  },
  {
    id: "st-015",
    firstName: "Aria",
    lastName: "Nakamura",
    dob: "2023-01-11",
    classroomId: "turtle",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Yuki Nakamura",
    guardianEmail: "yuki.nakamura@email.com",
    guardianPhone: "(503) 555-0174",
    enrollmentDate: "2023-09-18",
  },
  {
    id: "st-016",
    firstName: "Mason",
    lastName: "Okafor",
    dob: "2022-10-04",
    classroomId: "turtle",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Chidi Okafor",
    guardianEmail: "chidi.okafor@email.com",
    guardianPhone: "(503) 555-0182",
    enrollmentDate: "2023-06-05",
  },
  {
    id: "st-017",
    firstName: "Lila",
    lastName: "Andersson",
    dob: "2022-08-16",
    classroomId: "orca",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Erik Andersson",
    guardianEmail: "erik.andersson@email.com",
    guardianPhone: "(971) 555-0138",
    enrollmentDate: "2023-04-17",
  },
  {
    id: "st-018",
    firstName: "Henry",
    lastName: "Dubois",
    dob: "2022-05-22",
    classroomId: "orca",
    schedule: MWF,
    pottyTrained: true,
    status: "active",
    guardianName: "Claire Dubois",
    guardianEmail: "claire.dubois@email.com",
    guardianPhone: "(503) 555-0109",
    enrollmentDate: "2023-01-09",
  },
  {
    id: "st-019",
    firstName: "Nora",
    lastName: "Garcia",
    dob: "2022-02-14",
    classroomId: "orca",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Miguel Garcia",
    guardianEmail: "miguel.garcia@email.com",
    guardianPhone: "(503) 555-0151",
    enrollmentDate: "2022-10-03",
  },
  {
    id: "st-020",
    firstName: "Jack",
    lastName: "Thompson",
    dob: "2021-11-30",
    classroomId: "orca",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "active",
    guardianName: "Kate Thompson",
    guardianEmail: "kate.thompson@email.com",
    guardianPhone: "(971) 555-0179",
    enrollmentDate: "2022-07-11",
    notes: "Kindergarten start Fall 2026 — graduating July.",
  },
  {
    id: "st-021",
    firstName: "Ruby",
    lastName: "Chen",
    dob: "2025-05-01",
    classroomId: "shark",
    schedule: TTH,
    pottyTrained: false,
    status: "waitlist",
    guardianName: "Wei Chen",
    guardianEmail: "wei.chen@email.com",
    guardianPhone: "(503) 555-0194",
    enrollmentDate: "2026-06-01",
  },
  {
    id: "st-022",
    firstName: "Theo",
    lastName: "Morales",
    dob: "2024-09-12",
    classroomId: "starfish",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "waitlist",
    guardianName: "Ana Morales",
    guardianEmail: "ana.morales@email.com",
    guardianPhone: "(971) 555-0144",
    enrollmentDate: "2026-08-01",
  },
  {
    id: "st-023",
    firstName: "Ellie",
    lastName: "Park",
    dob: "2023-09-07",
    classroomId: "turtle",
    schedule: FULL_WEEK,
    pottyTrained: false,
    status: "active",
    guardianName: "Soo-jin Park",
    guardianEmail: "soojin.park@email.com",
    guardianPhone: "(503) 555-0125",
    enrollmentDate: "2024-05-20",
    notes: "Under 36 months in Turtle — exemption on file pending.",
  },
  {
    id: "st-024",
    firstName: "Finn",
    lastName: "O'Brien",
    dob: "2021-09-18",
    classroomId: "orca",
    schedule: FULL_WEEK,
    pottyTrained: true,
    status: "graduating",
    guardianName: "Siobhan O'Brien",
    guardianEmail: "siobhan.obrien@email.com",
    guardianPhone: "(503) 555-0160",
    enrollmentDate: "2022-05-02",
  },
];

export const ALERTS: Alert[] = [
  {
    id: "al-001",
    type: "age_transition",
    severity: "high",
    studentId: "st-005",
    title: "Mia Okonkwo eligible for Starfish",
    description:
      "Turns 20 months on Jul 8. Cascade recommends moving Octopus → Starfish to free an infant seat.",
    dueDate: "2026-08-01",
    acknowledged: false,
  },
  {
    id: "al-002",
    type: "age_transition",
    severity: "high",
    studentId: "st-011",
    title: "Harper Singh ready for Turtle",
    description:
      "Age and potty-trained status meet Turtle (Preschool 1) entry. Pull-up cascade frees Dolphin capacity.",
    dueDate: "2026-08-01",
    acknowledged: false,
  },
  {
    id: "al-003",
    type: "birthday",
    severity: "medium",
    studentId: "st-009",
    title: "Zoe Hassan birthday — Aug 3",
    description:
      "Turning 30 months. Remains age-eligible for Dolphin; review schedule for FTE gap pairing.",
    dueDate: "2026-08-03",
    acknowledged: false,
  },
  {
    id: "al-004",
    type: "exemption",
    severity: "high",
    studentId: "st-023",
    title: "Ellie Park — Turtle under-36 exemption",
    description:
      "Turtle allows max 2 children under 36 months. Ellie is currently under age; exemption documentation required.",
    dueDate: "2026-07-20",
    acknowledged: false,
  },
  {
    id: "al-005",
    type: "capacity",
    severity: "medium",
    studentId: "st-001",
    title: "Shark room at peak Friday FTE",
    description:
      "Friday headcount hits 11/12 legal seats. Delay new full-week enrollments until cascade opens a seat.",
    dueDate: "2026-07-18",
    acknowledged: true,
  },
  {
    id: "al-006",
    type: "birthday",
    severity: "low",
    studentId: "st-017",
    title: "Lila Andersson birthday — Aug 16",
    description: "Turning 4 years. Remains in Orca through school-age transition.",
    dueDate: "2026-08-16",
    acknowledged: false,
  },
  {
    id: "al-007",
    type: "age_transition",
    severity: "medium",
    studentId: "st-016",
    title: "Mason Okafor approaching Orca",
    description:
      "Will hit 48 months in Oct. Monthly shuffle engine flags Turtle → Orca if Orca vacancy exists.",
    dueDate: "2026-10-01",
    acknowledged: false,
  },
  {
    id: "al-008",
    type: "age_transition",
    severity: "low",
    studentId: "st-020",
    title: "Jack Thompson — kindergarten pipeline",
    description:
      "School-age transition Fall 2026. Orca seat opens August — prioritize Turtle pull-ups.",
    dueDate: "2026-08-15",
    acknowledged: false,
  },
];

export const TEAM: TeamMember[] = [
  {
    id: "tm-001",
    name: "Maya Chen",
    email: "maya.chen@littlenest.care",
    role: "Manager",
    avatar: "MC",
    task: "Reviewing August cascade recommendations",
    status: "In Progress",
    classroomFocus: "All rooms",
  },
  {
    id: "tm-002",
    name: "Daniel Ortiz",
    email: "daniel.ortiz@littlenest.care",
    role: "Admin",
    avatar: "DO",
    task: "Completed Q3 enrollment audit",
    status: "Completed",
    classroomFocus: "Center-wide",
  },
  {
    id: "tm-003",
    name: "Priya Shah",
    email: "priya.shah@littlenest.care",
    role: "Scheduler",
    avatar: "PS",
    task: "Pairing MWF/TTh FTE seats in Starfish",
    status: "In Progress",
    classroomFocus: "Starfish & Dolphin",
  },
  {
    id: "tm-004",
    name: "Jordan Lee",
    email: "jordan.lee@littlenest.care",
    role: "Scheduler",
    avatar: "JL",
    task: "Pending Turtle exemption paperwork",
    status: "Pending",
    classroomFocus: "Turtle",
  },
];

export const WEEKLY_CAPACITY = [
  { day: "M", label: "Mon", occupancy: 86, pending: false },
  { day: "T", label: "Tue", occupancy: 74, pending: false },
  { day: "W", label: "Wed", occupancy: 91, pending: false },
  { day: "T", label: "Thu", occupancy: 68, pending: false },
  { day: "F", label: "Fri", occupancy: 94, pending: false },
];

export const TRANSITION_RECS = [
  {
    id: "tr-001",
    studentId: "st-005",
    title: "Mia Okonkwo → Starfish",
    from: "Octopus",
    to: "Starfish",
    due: "Aug 1",
    icon: "shell" as const,
  },
  {
    id: "tr-002",
    studentId: "st-011",
    title: "Harper Singh → Turtle",
    from: "Dolphin",
    to: "Turtle",
    due: "Aug 1",
    icon: "leaf" as const,
  },
  {
    id: "tr-003",
    studentId: "st-016",
    title: "Mason Okafor → Orca",
    from: "Turtle",
    to: "Orca",
    due: "Oct 1",
    icon: "wave" as const,
  },
  {
    id: "tr-004",
    studentId: "st-008",
    title: "Ethan Walsh → Dolphin",
    from: "Starfish",
    to: "Dolphin",
    due: "Sep 1",
    icon: "star" as const,
  },
];
